<%@ Page Title="" Language="C#" MasterPageFile="~/PageMaster.Master" AutoEventWireup="true" CodeBehind="liste_delegue.aspx.cs" Inherits="Bon_c_belgiumpayment.liste_delegue" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <br />
<asp:Label ID="labeluser" runat="server"></asp:Label>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CellPadding="4" DataKeyNames="iddeleg" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:CommandField ShowSelectButton="True" />
            <asp:BoundField DataField="iddeleg" HeaderText="iddeleg" InsertVisible="False" ReadOnly="True" SortExpression="iddeleg" />
            <asp:BoundField DataField="nom" HeaderText="nom" SortExpression="nom" />
            <asp:BoundField DataField="prenom" HeaderText="prenom" SortExpression="prenom" />
            <asp:BoundField DataField="login_" HeaderText="login_" SortExpression="login_" />
        </Columns>
        <EditRowStyle BackColor="#2461BF" />
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F5F7FB" />
        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
        <SortedDescendingCellStyle BackColor="#E9EBEF" />
        <SortedDescendingHeaderStyle BackColor="#4870BE" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Bon_de_commandeConnectionString %>" SelectCommand="SELECT [iddeleg], [nom], [prenom], [login_] FROM [delegue]" DeleteCommand="delete from [delegue] where [iddeleg]=@iddeleg" OnSelecting="SqlDataSource1_Selecting"></asp:SqlDataSource>
    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" CellPadding="4" DataKeyNames="iddeleg" DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None" Height="50px" Width="125px" AutoGenerateEditButton="True">
        <AlternatingRowStyle BackColor="White" />
        <CommandRowStyle BackColor="#D1DDF1" Font-Bold="True" />
        <EditRowStyle BackColor="#2461BF" />
        <FieldHeaderStyle BackColor="#DEE8F5" Font-Bold="True" />
        <Fields>
            <asp:BoundField DataField="iddeleg" HeaderText="iddeleg" InsertVisible="False" ReadOnly="True" SortExpression="iddeleg" />
            <asp:BoundField DataField="nom" HeaderText="nom" SortExpression="nom" />
            <asp:BoundField DataField="prenom" HeaderText="prenom" SortExpression="prenom" />
            <asp:BoundField DataField="gsm" HeaderText="gsm" SortExpression="gsm" />
            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
            <asp:BoundField DataField="login_" HeaderText="login_" SortExpression="login_" />
            <asp:BoundField DataField="mot_de_passe" HeaderText="mot_de_passe" SortExpression="mot_de_passe" />
            <asp:BoundField DataField="admin_" HeaderText="admin_" SortExpression="admin_" />
        </Fields>
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
    </asp:DetailsView>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:Bon_de_commandeConnectionString %>" SelectCommand="SELECT * FROM [delegue] WHERE ([iddeleg] = @iddeleg)" UpdateCommand="update [delegue] set [nom]=@nom,[prenom]=@prenom,[gsm]=@gsm,[email]=@email,[login_]=@login_,[mot_de_passe]=@mot_de_passe,[admin_]=@admin_ where [iddeleg]=@iddeleg">
        <SelectParameters>
            <asp:ControlParameter ControlID="GridView1" Name="iddeleg" PropertyName="SelectedValue" Type="Int32" />
        </SelectParameters>
    </asp:SqlDataSource>

</asp:Content>
